### ISSUE TITLE
React-group-project: CAnban board setup

### ISSUE THREAD

**Issue by Melaku05** [Melaku05/React-group-project#27]
Create React App.
    Install [React Redux](https://react-redux.js.org/), [Redux Logger](https://www.npmjs.com/package/redux-logger) and [React Router](https://reactrouter.com/web/guides/quick-start).

**Comment by Kingstalux** [comment]
Hi @Melaku05 and @AnicetFantomas , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ❌ 

- [ ] Kindly provide the link to your Github project and not your Github repo. This is the correct [link](https://github.com/Melaku05/React-group-project/projects/1).
- [ ] Also, kindly check your total number of cards and make sure that all cards for teams of two are present and have assignees 👍 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
