### ISSUE TITLE
React-group-project: Canban board setup

### ISSUE THREAD

**Issue by Melaku05** [Melaku05/React-group-project#28]
https://github.com/Melaku05/React-group-project/projects/1
we Are @Melaku05  and @AnicetFantomas

**Comment by julie-ify** [comment]
## Hi @Melaku05 and @AnicetFantomas,

Good job so far!

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️
_Check the comments under the review._

- [ ] The first group task is not included in your Kanban board, instead, you added a Kanban board setup. Kindly replace the Kanban setup task with the correct task which I attached below. Also do not forget to include the point needed to complete it.

Your Implementation | The template
:---:|:---:
![](https://i.imgur.com/9p5AwBA.png) | ![](https://i.imgur.com/zsJTmPV.png)



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@julie-ify` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Melaku05** [comment]
Thank you, We did that.

**Comment by uwadonat** [comment]
Hi **@Team,** 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations!  🎉 
![appr3](https://user-images.githubusercontent.com/65860678/168774287-0afae799-2e7c-4fcc-923a-ad19a6956914.gif)


# Status: Approved ✔️✔️✔️

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by Melaku05** [comment]
Thank you
